// Mocks generated by Mockito 5.4.6 from annotations
// in interval_timer_app/test/features/settings/settings_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:interval_timer_app/core/domain/group_node.dart' as _i6;
import 'package:interval_timer_app/core/domain/timer_preset.dart' as _i4;
import 'package:interval_timer_app/core/services/storage_service.dart' as _i3;
import 'package:interval_timer_app/features/settings/domain/settings_domain.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSettings_0 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.TimerPreset> loadPresets() =>
      (super.noSuchMethod(
            Invocation.method(#loadPresets, []),
            returnValue: <_i4.TimerPreset>[],
          )
          as List<_i4.TimerPreset>);

  @override
  _i5.Future<void> savePresets(List<_i4.TimerPreset>? presets) =>
      (super.noSuchMethod(
            Invocation.method(#savePresets, [presets]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i6.GroupNode> loadRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#loadRoutines, []),
            returnValue: <_i6.GroupNode>[],
          )
          as List<_i6.GroupNode>);

  @override
  _i5.Future<void> saveRoutines(List<_i6.GroupNode>? routines) =>
      (super.noSuchMethod(
            Invocation.method(#saveRoutines, [routines]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isStartCueEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isStartCueEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> setStartCueEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setStartCueEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isEndCueEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isEndCueEnabled, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> setEndCueEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setEndCueEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Settings loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _FakeSettings_0(
              this,
              Invocation.method(#loadSettings, []),
            ),
          )
          as _i2.Settings);

  @override
  _i5.Future<void> saveSettings(_i2.Settings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [settings]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
