// Mocks generated by Mockito 5.4.6 from annotations
// in interval_timer_app/test/groups_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:interval_timer_app/models/timer_group.dart' as _i5;
import 'package:interval_timer_app/models/timer_preset.dart' as _i3;
import 'package:interval_timer_app/services/storage_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.TimerPreset> loadPresets() =>
      (super.noSuchMethod(
            Invocation.method(#loadPresets, []),
            returnValue: <_i3.TimerPreset>[],
          )
          as List<_i3.TimerPreset>);

  @override
  _i4.Future<void> savePresets(List<_i3.TimerPreset>? presets) =>
      (super.noSuchMethod(
            Invocation.method(#savePresets, [presets]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i5.TimerGroup> loadGroups() =>
      (super.noSuchMethod(
            Invocation.method(#loadGroups, []),
            returnValue: <_i5.TimerGroup>[],
          )
          as List<_i5.TimerGroup>);

  @override
  _i4.Future<void> saveGroups(List<_i5.TimerGroup>? groups) =>
      (super.noSuchMethod(
            Invocation.method(#saveGroups, [groups]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
